<a href="https://colab.research.google.com/github/NiveditaB444/IS-597-MLC-/blob/main/NiveditaBharti_Week_3_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np #Importing numpy
np.__version__ #Verifying the version importedd

'1.26.4'

In [4]:
delivery_times = np.random.randint(30, 121, size=100) # 1D array for delivery times (100 random int)
delivery_times

array([112, 117,  40,  60,  77,  36, 103,  64,  40,  45,  55,  47, 100,
       118, 117,  56,  75,  77,  98, 104,  71,  95,  75, 102, 117,  51,
        75,  85,  43, 111,  77,  99,  95,  45,  56,  82,  97, 103,  58,
        90,  98,  58, 118,  84, 106,  76, 115,  58, 101,  42,  95, 115,
       117,  98,  39,  94, 102,  46,  98, 104,  74, 100,  67,  52,  69,
        66, 103,  82,  52,  73,  31, 104, 114,  34,  47,  60,  38,  43,
        41, 107, 103, 116,  56,  60, 103,  75,  73,  57, 105,  55,  65,
        58,  62, 110,  74,  45,  31,  88,  38,  53])

In [5]:
package_weights = np.round(np.random.uniform(0.5, 10.0, size=100), 2) # 1D array for package wegihts

array([4.38, 2.82, 8.01, 5.18, 8.25, 2.39, 3.75, 0.56, 9.96, 2.38, 1.28,
       6.74, 7.49, 6.98, 1.42, 5.88, 9.28, 5.47, 8.96, 2.66, 8.07, 0.96,
       0.5 , 8.6 , 1.94, 8.39, 2.75, 1.53, 2.18, 5.87, 8.44, 9.71, 1.02,
       2.92, 2.43, 3.76, 8.71, 1.52, 8.97, 1.11, 7.68, 2.19, 6.99, 8.26,
       2.1 , 8.94, 8.59, 2.04, 7.8 , 3.68, 6.52, 6.49, 9.4 , 3.64, 9.14,
       7.13, 8.3 , 6.53, 7.06, 2.77, 3.88, 7.95, 5.15, 0.79, 6.01, 4.29,
       4.05, 3.97, 7.09, 9.14, 7.62, 0.63, 2.57, 7.73, 5.22, 3.08, 7.41,
       4.83, 9.31, 9.93, 3.31, 6.93, 3.68, 7.44, 6.68, 1.41, 4.73, 3.75,
       3.57, 2.48, 1.56, 5.38, 4.19, 9.81, 4.39, 4.46, 9.25, 1.64, 0.81,
       2.29])

In [25]:
data= np.column_stack((delivery_times.astype(int), package_weights)) #creating 2D array
print(data)

[[112.     4.38]
 [117.     2.82]
 [ 40.     8.01]
 [ 60.     5.18]
 [ 77.     8.25]
 [ 36.     2.39]
 [103.     3.75]
 [ 64.     0.56]
 [ 40.     9.96]
 [ 45.     2.38]
 [ 55.     1.28]
 [ 47.     6.74]
 [100.     7.49]
 [118.     6.98]
 [117.     1.42]
 [ 56.     5.88]
 [ 75.     9.28]
 [ 77.     5.47]
 [ 98.     8.96]
 [104.     2.66]
 [ 71.     8.07]
 [ 95.     0.96]
 [ 75.     0.5 ]
 [102.     8.6 ]
 [117.     1.94]
 [ 51.     8.39]
 [ 75.     2.75]
 [ 85.     1.53]
 [ 43.     2.18]
 [111.     5.87]
 [ 77.     8.44]
 [ 99.     9.71]
 [ 95.     1.02]
 [ 45.     2.92]
 [ 56.     2.43]
 [ 82.     3.76]
 [ 97.     8.71]
 [103.     1.52]
 [ 58.     8.97]
 [ 90.     1.11]
 [ 98.     7.68]
 [ 58.     2.19]
 [118.     6.99]
 [ 84.     8.26]
 [106.     2.1 ]
 [ 76.     8.94]
 [115.     8.59]
 [ 58.     2.04]
 [101.     7.8 ]
 [ 42.     3.68]
 [ 95.     6.52]
 [115.     6.49]
 [117.     9.4 ]
 [ 98.     3.64]
 [ 39.     9.14]
 [ 94.     7.13]
 [102.     8.3 ]
 [ 46.     6.53]
 [ 98.     7.0

#TASK 2


In [14]:
mean_delivery = np.mean(delivery_times) #Mean, median, std delivery, max delivery for delivery times array
median_delivery = np.median(delivery_times)
standard_delivery = np.std(delivery_times)
max_delivery = np.max(delivery_times)
mean_delivery, median_delivery, standard_delivery, max_delivery

(77.16, 75.0, 26.158639108332835, 118)

In [16]:
mean_weight = np.mean(package_weights) #mean, minimum, range of weights for package weights array
min_weight = np.min(package_weights)
range_weight = np.ptp(package_weights)
mean_weight, min_weight, range_weight

(5.168799999999999, 0.5, 9.46)

In [17]:
MoreThan90 = np.sum(delivery_times > 90)
MoreThan90

39

#Task 3


In [26]:
heavy_packages = data[data[:, 1] > 5] # New array for packages>5kg
heavy_fast_count = np.sum(heavy_packages[:, 0] <= 60) # No. of deliveries from heavy packages where delivery time<=60
heavy_packages, heavy_fast_count


(array([[ 40.  ,   8.01],
        [ 60.  ,   5.18],
        [ 77.  ,   8.25],
        [ 40.  ,   9.96],
        [ 47.  ,   6.74],
        [100.  ,   7.49],
        [118.  ,   6.98],
        [ 56.  ,   5.88],
        [ 75.  ,   9.28],
        [ 77.  ,   5.47],
        [ 98.  ,   8.96],
        [ 71.  ,   8.07],
        [102.  ,   8.6 ],
        [ 51.  ,   8.39],
        [111.  ,   5.87],
        [ 77.  ,   8.44],
        [ 99.  ,   9.71],
        [ 97.  ,   8.71],
        [ 58.  ,   8.97],
        [ 98.  ,   7.68],
        [118.  ,   6.99],
        [ 84.  ,   8.26],
        [ 76.  ,   8.94],
        [115.  ,   8.59],
        [101.  ,   7.8 ],
        [ 95.  ,   6.52],
        [115.  ,   6.49],
        [117.  ,   9.4 ],
        [ 39.  ,   9.14],
        [ 94.  ,   7.13],
        [102.  ,   8.3 ],
        [ 46.  ,   6.53],
        [ 98.  ,   7.06],
        [100.  ,   7.95],
        [ 67.  ,   5.15],
        [ 69.  ,   6.01],
        [ 52.  ,   7.09],
        [ 73.  ,   9.14],
        [ 31

#Task 4


In [28]:
min_time, max_time = np.min(delivery_times), np.max(delivery_times)
norm_delivery_times = (delivery_times - min_time) / (max_time - min_time) #Normalization of delivery times
logistics_data = np.column_stack((data, norm_delivery_times))  # Adding the normalized values as a third column in the data
Sorted_Data = data[np.argsort(data[:, 1])[::-1]]
Sorted_Data


array([[ 40.  ,   9.96],
       [107.  ,   9.93],
       [110.  ,   9.81],
       [ 99.  ,   9.71],
       [117.  ,   9.4 ],
       [ 41.  ,   9.31],
       [ 75.  ,   9.28],
       [ 31.  ,   9.25],
       [ 39.  ,   9.14],
       [ 73.  ,   9.14],
       [ 58.  ,   8.97],
       [ 98.  ,   8.96],
       [ 76.  ,   8.94],
       [ 97.  ,   8.71],
       [102.  ,   8.6 ],
       [115.  ,   8.59],
       [ 77.  ,   8.44],
       [ 51.  ,   8.39],
       [102.  ,   8.3 ],
       [ 84.  ,   8.26],
       [ 77.  ,   8.25],
       [ 71.  ,   8.07],
       [ 40.  ,   8.01],
       [100.  ,   7.95],
       [101.  ,   7.8 ],
       [ 34.  ,   7.73],
       [ 98.  ,   7.68],
       [ 31.  ,   7.62],
       [100.  ,   7.49],
       [ 60.  ,   7.44],
       [ 38.  ,   7.41],
       [ 94.  ,   7.13],
       [ 52.  ,   7.09],
       [ 98.  ,   7.06],
       [118.  ,   6.99],
       [118.  ,   6.98],
       [116.  ,   6.93],
       [ 47.  ,   6.74],
       [103.  ,   6.68],
       [ 46.  ,   6.53],


# Task 5

In [29]:
categories = np.where(delivery_times <= 60, 'A', np.where(delivery_times <= 90, 'B', 'C'))
categories = categories[:, np.newaxis]
data_with_categories = np.column_stack((data, categories))

AvgWeight_A = np.mean(package_weights[delivery_times <= 60])
AvgWeight_B = np.mean(package_weights[(delivery_times > 60) & (delivery_times <= 90)])
AvgWeight_C = np.mean(package_weights[delivery_times > 90])

AvgWeight_A, AvgWeight_B, AvgWeight_C



(5.080833333333334, 4.6912, 5.556153846153846)

#Insights

In [38]:
Overall_Insights= f"""
1. Average package weight per category:
   - Category A (<=60 min): {AvgWeight_A:.2f} kg
   - Category B (61-90 min): {AvgWeight_B:.2f} kg
   - Category C (>90 min): {AvgWeight_C:.2f} kg

2. There are {len(heavy_packages)} heavy packages (weight > 5 kg), and {heavy_fast_count} were delivered in 60 minutes or less.

3. The minimum weight is {min_weight:.2f} kg and mean weight is {mean_weight:.2f} kg."""

print(" ".join(Overall_Insights.splitlines()))

 1. Average package weight per category:    - Category A (<=60 min): 5.08 kg    - Category B (61-90 min): 4.69 kg    - Category C (>90 min): 5.56 kg  2. There are 50 heavy packages (weight > 5 kg), and 18 were delivered in 60 minutes or less.  3. The minimum weight is 0.50  and mean weight is 5.17
